Repository ruthlennonatu/marvel22, pull requests merged in 2022-11, with the labels that each got.

#126 Create ResearchOnDBs.txt
  ResearchOnDBs.txt
Labels: documentation

#131 Resolves #128 via DatabaseResearch.docx
  DatabaseResearch.docx
  DbResearch.docx
Labels: good first issue

#155 Script for checking current Grade
  GDPR Data Privacy Articles.txt
  SecurityInfoB.docx
  checkCurrGrade.txt
Labels: enhancement
